### PR TITLE
Moves / Migrates project to .NET standard

### PR DESCRIPTION
**Pull request by san983**
Taking the path stated in https://github.com/dnsimple/dnsimple-csharp/pull/10 by @adamfisher (🙇). Note:I was not able to follow up in the original PR since it looks the branch/fork has been deleted by the author. 

This PR migrates the client to .NET standard in order to make it broadly supported for the whole .NET ecosystem.

### CODE REVIEW

**Comment by ggalmazor** [comment]
Do we need to update the `README` or `CONTRIBUTING` docs, @san983?

**Comment by san983** [comment]
> Do we need to update the `README` or `CONTRIBUTING` docs, @san983?

As far as I see, there is no need. But I'm open to suggestions :)

**Comment by ggalmazor** [comment]
I think I need a bit of help. I'm getting the following error when running `./build.sh`:

```
MacBook-Pro~/src/dnsimple/dnsimple-csharp(move-to-net-standard|✔) % ./build.sh
Feeds used:
  /Users/guillermo/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /Users/guillermo/src/dnsimple/dnsimple-csharp/tools/packages.config are already installed.

========================================
Clean
========================================

========================================
Restore-NuGet-Packages
========================================
MSBuild auto-detection: using msbuild version '15.0' from '/usr/local/Cellar/mono/6.8.0.123/lib/mono/msbuild/15.0/bin'.
/usr/local/Cellar/mono/6.8.0.123/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/Users/guillermo/src/dnsimple/dnsimple-csharp/src/dnsimple-test/dnsimple-test.csproj]

An error occurred when executing task 'Restore-NuGet-Packages'.
Error: One or more errors occurred. (NuGet: Process returned an error (exit code 1).)
	NuGet: Process returned an error (exit code 1).
```

My mono version is:
```
MacBook-Pro~/src/dnsimple/dnsimple-csharp(move-to-net-standard|✔) % mono --version
Mono JIT compiler version 6.8.0.123 (tarball Fri May 15 17:28:53 BST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Review by ggalmazor — APPROVED** [review]
LGTM! I was able to build the project once I installed Visual Studio for mac. FWIW, mono installed with Homebrew didn't work for me.

**Review by duduribeiro — APPROVED** [review]
💯 

Looks good to me @san983

**Pull request merged**
