### PR TITLE
Migrated to .NET Standard for broader support and compabitibility.

### PR DESCRIPTION
**Pull request by adamfisher**
Converted the library to .NET standard. I got most of the tests passing but there are still 14 failing and it would be good to get someone who actually worked on this to review these remaining tests.

### CODE REVIEW

**Comment by ecomba** [comment]
Thank you for the PR @adamfisher. 

I have checked it and found that the tests did not pass because of the targeted framework in the dnsimple-test project is set to netcoreapp 3.1:

`<TargetFramework>netcoreapp3.1</TargetFramework>`

If you change this to `<TargetFramework>netcoreapp2.1</TargetFramework>` the tests pass.

I have a question, what prompted you to delete the `dnsimple.nuspec` file?

**Comment by adamfisher** [comment]
@weppos I thought the nuspec file was no longer needed since the csproj file now contains nuget package metadata and that is where it would be maintained. Added it back for now. When can we expect a new nuget package? Thanks!

**Comment by weppos** [comment]
> @weppos I thought the nuspec file was no longer needed since the csproj file now contains nuget package metadata and that is where it would be maintained.

Thanks, we'll look into that.

> When can we expect a new nuget package? Thanks!

0.9.0 was published on NuGet ~1 month ago
https://www.nuget.org/packages/DNSimple/

We'll continue to publish new releases as we make improvements.

**Comment by CumpsD** [comment]
Looking forward to this becoming a net standard or netcore lib, now I am getting:

```
xxx.csproj : warning NU1701: Package 'DNSimple 0.9.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```

**Comment by san983** [comment]
Closing in favour of https://github.com/dnsimple/dnsimple-csharp/pull/23

**Pull request closed without merging**
