### PR TITLE
Add JSON payload without serialization

### PR DESCRIPTION
**Pull request by VanHuychemG**
Add JSON payload method without serialization first to prevent string arrays/list being escaped in the request.

image

### CODE REVIEW

**Comment by san983** [comment]
Thanks @VanHuychemG! I'm triaging this PR to be discussed and prioritised by the team.

**Comment by san983** [comment]
Hi @VanHuychemG, sorry for the delay. 

We went thru this and we haven't found a reason about why sending an unserialized body. May I ask if are sending the list of nameservers as in the example below?

```csharp
var delegation = new List<string>
{
    "ns1.dnsimple.com", "ns2.dnsimple.com", "ns3.dnsimple.com","ns4.dnsimple.com"
};

var newDelegation = client.Registrar.ChangeDomainDelegation(accountId, domainName, delegation);
```

**Comment by SProfession** [comment]
I'm currently seeing this issue as well, using your described example, passing in a list causes the Payload to fail with the reason above:
image

Here is the request object serialized:
image

Responses' Request Body:
image


> 
> 
> Hi @VanHuychemG, sorry for the delay.
> 
> We went thru this and we haven't found a reason about why sending an unserialized body. May I ask if are sending the list of nameservers as in the example below?
> 
> ```cs
> var delegation = new List<string>
> {
>     "ns1.dnsimple.com", "ns2.dnsimple.com", "ns3.dnsimple.com","ns4.dnsimple.com"
> };
> 
> var newDelegation = client.Registrar.ChangeDomainDelegation(accountId, domainName, delegation);
> ```

**Comment by ecomba** [comment]
Reopened this PR.

I was looking into #57 and started investigating (and trying to see if it is a legitimate error; it is). I found this PR and tried the code out to and it actually does solve the issue. 👍🏼 

Thank you @VanHuychemG for this and sorry for the delay

**Review by ecomba — COMMENTED** [review]
Looks good to me! 👍🏼

**Pull request merged**
